// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDOGq_ncLpcpQvcOgdn515yIRAOHm9x4',
    appId: '1:732825489585:web:f099bfd38bcfeeb9d11290',
    messagingSenderId: '732825489585',
    projectId: 'cuidpet-eae07',
    authDomain: 'cuidpet-eae07.firebaseapp.com',
    storageBucket: 'cuidpet-eae07.appspot.com',
    measurementId: 'G-J601YV225V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdnhXYRbmAE1YHQgFkRzEiZNwDoQ5stpY',
    appId: '1:732825489585:android:aee289c052002b58d11290',
    messagingSenderId: '732825489585',
    projectId: 'cuidpet-eae07',
    storageBucket: 'cuidpet-eae07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbrgUnvebcYjFc8D9Z_sE15yj8j0lQyWM',
    appId: '1:732825489585:ios:99e1ce01220b2654d11290',
    messagingSenderId: '732825489585',
    projectId: 'cuidpet-eae07',
    storageBucket: 'cuidpet-eae07.appspot.com',
    iosClientId: '732825489585-tpma05ffvdp336cpqftv4ekq3075m913.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCuidpet',
  );
}
